// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjWYyZPBU2B0Db-mDemjVX5QkRxcZLdzg',
    appId: '1:702088212153:web:6a88f92202c0a96fc03568',
    messagingSenderId: '702088212153',
    projectId: 'flutter-e-commerce-nike',
    authDomain: 'flutter-e-commerce-nike.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-nike.appspot.com',
    measurementId: 'G-BCNW6DS5T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAawzITPJ3eVmuca3zevsOIiLNCjrg95KI',
    appId: '1:702088212153:android:73bee6e79649c865c03568',
    messagingSenderId: '702088212153',
    projectId: 'flutter-e-commerce-nike',
    storageBucket: 'flutter-e-commerce-nike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3k8zwVfVm5_mISv2hxygcbaJ4JCHBc4',
    appId: '1:702088212153:ios:1d9ee1968ea650b0c03568',
    messagingSenderId: '702088212153',
    projectId: 'flutter-e-commerce-nike',
    storageBucket: 'flutter-e-commerce-nike.appspot.com',
    iosBundleId: 'com.example.nikeECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE3k8zwVfVm5_mISv2hxygcbaJ4JCHBc4',
    appId: '1:702088212153:ios:42b2005d329bb2c1c03568',
    messagingSenderId: '702088212153',
    projectId: 'flutter-e-commerce-nike',
    storageBucket: 'flutter-e-commerce-nike.appspot.com',
    iosBundleId: 'com.example.nikeECommerce.RunnerTests',
  );
}
